SELECT ANIMAL_ID, NAME
FROM (
    SELECT 
        I.ANIMAL_ID,
        I.NAME,
        O.DATETIME - I.DATETIME AS PROTECT,
        RANK() OVER (ORDER BY O.DATETIME - I.DATETIME DESC) AS RANK
    FROM ANIMAL_INS I
    JOIN ANIMAL_OUTS O ON I.ANIMAL_ID = O.ANIMAL_ID
) P
WHERE P.RANK <= 2
ORDER BY PROTECT DESC;