SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK B JOIN BOOK_SALES S ON B.BOOK_ID = S.BOOK_ID 
WHERE SUBSTR(TO_CHAR(S.SALES_DATE, 'YYYY-MM-DD'), 1, 4) = '2022' AND SUBSTR(TO_CHAR(S.SALES_DATE, 'YYYY-MM-DD'), 6, 2) = '01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY;
